### ISSUE TITLE
Use templates for OpenFaaS Python function

### ISSUE THREAD

**Issue by alexellis** [lekum/serverless-with-python#1]
Hey, thanks for writing this sample for OpenFaaS

https://github.com/lekum/serverless-with-python/tree/master/DIY/openfaas

Just wanted to introduce you to the template concept which can be used through the CLI.

No more reading from stdin etc.

https://blog.alexellis.io/quickstart-openfaas-cli/

**Comment by lekum** [comment]
Hi @alexellis,

Thank you very much for creating OpenFaaS and also for reaching me. I created that nano-tutorial manually building the image because I only wanted to make examples with **Python 3** and it was not available as a `--lang` option for the `faas-cli`. Thanks,

**Comment by alexellis** [comment]
We have community template support coming soon and Python3 should be an official option if you want to raise an issue or send a pull request

**Comment by lekum** [comment]
Thanks! I'm using this repo as support material for a talk tomorrow at PyConES (Spain) and I needed examples in Python 3, later I would gladly contribute to an official option in the CLI.

Thanks,
